### ISSUE TITLE
feat(native): create native image

### ISSUE THREAD

**Issue by DarkAtra** [DarkAtra/v-rising-discord-bot#63]
**The issue**
One of the biggest drawbacks of this bot is its memory consumption. With the recent upgrade to Spring Boot 3 we could try to build a native image using GraalVM.

**Proposed solution**
Configure the spring-boot-maven-plugin so that it builds a native image via GraalVM. This would result in near instant startup times and lower memory consumption for the bot. It would also eliminate the need for a JVM.

**Notes**
I've already attempted to build a native image when Spring Boot 3 was released and it didn't work out of the box. The main issue back then was that kotlin coroutines didn't play nicely with native image, see: https://github.com/oracle/graal/issues/5606. Also, the database is using jackson for serialization, e.g. runtime hints are required, see: https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/aot/hint/annotation/RegisterReflectionForBinding.html

**Comment by DarkAtra** [comment]
Related:
* https://github.com/nitrite/nitrite-java/issues/403
* https://github.com/kordlib/kord/issues/786
* https://github.com/ribasco/async-gamequery-lib/issues/165

**Comment by DarkAtra** [comment]
added hints:
* https://github.com/DarkAtra/v-rising-discord-bot/blob/next/src/main/kotlin/de/darkatra/vrising/discord/Bot.kt#L35
* https://github.com/DarkAtra/v-rising-discord-bot/blob/next/src/main/kotlin/de/darkatra/vrising/discord/BotRuntimeHints.kt

**Comment by DarkAtra** [comment]
The above issue can be avoided on linux by passing `-Dagql.nativeTransport=false` as an argument to the docker image or the executable.

Example for docker-compose:
```
services:
  v-rising-discord-bot:
    image: ghcr.io/darkatra/v-rising-discord-bot:2.0.6-next.3-native
    command: -Dagql.nativeTransport=false
    mem_reservation: 256M
    mem_limit: 512M
    volumes:
      - /opt/v-rising-discord-bot:/data/v-rising-discord-bot
    environment:
      - BOT_DISCORD_BOT_TOKEN=<your-discord-bot-token>
      - BOT_DATABASE_PATH=/data/v-rising-discord-bot/bot.db
      - BOT_DATABASE_PASSWORD=<the-database-password>
    restart: unless-stopped
```
