### ISSUE TITLE
bug: native builds failing in Github Workflows

### ISSUE THREAD

**Issue by DarkAtra** [DarkAtra/v-rising-discord-bot#90]
The native builds are currently failing on Github for some reason. I suspect a change in GraalVM. Local builds with "older" GraalVM versions work just fine.

**Comment by DarkAtra** [comment]
builds work with graalvm `22.3.2`:
```
      - uses: graalvm/setup-graalvm@v1.0.12
        with:
          java-version: '17'
          # distribution: 'graalvm'
          version: '22.3.2'
          components: 'native-image'
```
